# Generated by Django 5.2.12 on 2026-04-06 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('category', models.CharField(choices=[('landmark', 'Landmark'), ('restaurant', 'Restaurant'), ('hotel', 'Hotel')], verbose_name='Category')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(db_column='description', verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Availability')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Original date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last date')),
            ],
        ),
        migrations.CreateModel(
            name='BookableService',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.place')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
            ],
            bases=('places.place',),
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Original date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last date')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Place')),
            ],
        ),
    ]
