# Generated by Django 5.2.12 on 2026-04-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_slide_description_slide_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='updated_at',
        ),
    ]
